@namespace
class SpriteKind:
    Switch = SpriteKind.create()

def on_hit_wall(sprite, location):
    global flying
    if not (sprite.is_hitting_tile(CollisionDirection.BOTTOM)):
        game.over(False)
    elif terminalVelocity():
        game.over(False)
    if flying:
        if tiles.tile_at_location_equals(location, sprites.dungeon.purple_switch_up):
            tiles.set_tile_at(location, sprites.dungeon.green_switch_down)
            flying = 0
        elif tiles.tile_at_location_equals(location, sprites.dungeon.green_switch_down):
            tiles.set_tile_at(location, sprites.dungeon.purple_switch_up)
            flying = 0
scene.on_hit_wall(SpriteKind.player, on_hit_wall)

def on_a_pressed():
    global flying
    console.log_value("on_a_pressed", flying)
    mySprite.ay += thrust
    flying = 1
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_left_pressed():
    mySprite.ax += thrust
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def transform_tiles():
    for index in range(100):
        x = randint(0, 160)
        y = randint(0, 160)
        tile_type = get_tile_type(x, y)

def on_right_released():
    mySprite.ax += thrust
controller.right.on_event(ControllerButtonEvent.RELEASED, on_right_released)

def on_left_released():
    mySprite.ax += 0 - thrust
controller.left.on_event(ControllerButtonEvent.RELEASED, on_left_released)

def on_right_pressed():
    mySprite.ax += 0 - thrust
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_a_released():
    mySprite.ay += 0 - thrust
controller.A.on_event(ControllerButtonEvent.RELEASED, on_a_released)

def get_tile_type(x: number, y: number):
    location = tiles.get_tile_location(x, y)
    if tiles.tile_at_location_equals(location, sprites.dungeon.green_switch_down):
        return 1
    elif tiles.tile_at_location_equals(location, sprites.dungeon.purple_switch_down):
        return -1

    return 0
def terminalVelocity():
    return mySprite.vy > 25
flying = 0
thrust = 0
mySprite: Sprite = None
scene.set_background_color(12)
tiles.set_tilemap(tilemap("""
    level1
"""))
mySprite = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . b 5 5 b . . . 
            . . . . . . b b b b b b . . . . 
            . . . . . b b 5 5 5 5 5 b . . . 
            . b b b b b 5 5 5 5 5 5 5 b . . 
            . b d 5 b 5 5 5 5 5 5 5 5 b . . 
            . . b 5 5 b 5 d 1 f 5 d 4 f . . 
            . . b d 5 5 b 1 f f 5 4 4 c . . 
            b b d b 5 5 5 d f b 4 4 4 4 b . 
            b d d c d 5 5 b 5 4 4 4 4 4 4 b 
            c d d d c c b 5 5 5 5 5 5 5 b . 
            c b d d d d d 5 5 5 5 5 5 5 b . 
            . c d d d d d d 5 5 5 5 5 d b . 
            . . c b d d d d d 5 5 5 b b . . 
            . . . c c c c c c c c b b . . .
    """),
    SpriteKind.player)
mySprite.set_position(16, 460)
mySprite.set_position(1970, 1000)
scene.camera_follow_sprite(mySprite)
mySprite.ay = 20
mySprite.fx = 5
mySprite.fy = 5
thrust = -100
terminal_velocity = 25
flying = 1

def on_update_interval():
    transform_tiles()
game.on_update_interval(1000, on_update_interval)

def on_update_interval2():
    if terminalVelocity():
        if mySprite.ax > 0:
            mySprite.set_image(img("""
                .......fff..............
                                ..........fffff.........
                                ......fff....fffff......
                                .........fffff....fff...
                                .............fffff......
                                .............f....fff...
                                ............f...........
                                ......ffff..f...........
                                ......f111ffffff........
                                ......f1111f1111fff.....
                                ......f1111f111111f.....
                                .....f11111f11111f......
                                .....f11111f11111f......
                                .....f11111111111f......
                                ....f11111111111f.......
                                ....fff111111111f.......
                                .......ffffff111f.......
                                .............ffff.......
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
            """))
        elif mySprite.ax < 0:
            mySprite.set_image(img("""
                ..............fff.......
                                .........fffff..........
                                ......fffff....fff......
                                ...fff....fffff.........
                                ......fffff.............
                                ...fff....f.............
                                ...........f............
                                ...........f..ffff......
                                ........ffffff111f......
                                .....fff1111f1111f......
                                .....f111111f1111f......
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111111111f.....
                                .......f11111111111f....
                                .......f111111111fff....
                                .......f111ffffff.......
                                .......ffff.............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
            """))
        elif mySprite.vx > 0:
            mySprite.set_image(img("""
                ........................
                                ........................
                                .....fffffffffffffff....
                                ............f...........
                                .....fffffffffffffff....
                                ............f...........
                                ............f...........
                                ............f...........
                                ......fffffffffffff.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111111111f.....
                                ......f11111111111f.....
                                ......f11111111111f.....
                                ......fffffffffffff.....
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
            """))
        elif mySprite.vy < 0:
            mySprite.set_image(img("""
                ........................
                                ........................
                                .....fffffffffffffff....
                                ............f...........
                                .....fffffffffffffff....
                                ............f...........
                                ............f...........
                                ............f...........
                                ......fffffffffffff.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111111111f.....
                                ......f11111111111f.....
                                ......f11111111111f.....
                                ......fffffffffffff.....
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
            """))
        else:
            mySprite.set_image(img("""
                ........................
                                ........................
                                .....fffffffffffffff....
                                ............f...........
                                .....fffffffffffffff....
                                ............f...........
                                ............f...........
                                ............f...........
                                ......fffffffffffff.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111f11111f.....
                                ......f11111111111f.....
                                ......f11111111111f.....
                                ......f11111111111f.....
                                ......fffffffffffff.....
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
            """))
    elif mySprite.ax > 0:
        mySprite.set_image(img("""
            .......fff..............
                        ..........fffff.........
                        ......fff....fffff......
                        .........fffff....fff...
                        .............fffff......
                        .............f....fff...
                        ............f...........
                        ......ffff..f...........
                        ......f111ffffff........
                        .....ff1111f1111fff.....
                        ....f.f1111f111111f.....
                        ....ff11111f11111ff.....
                        ...f.f11111f11111ff.....
                        ...f.f11111111111ff.....
                        ..f.f11111111111f.f.....
                        .f..fff111111111f.f.....
                        .f.....ffffff111f.f.....
                        f............ffff.f.....
                        ..................f.....
                        ..................f.....
                        ..................f.....
                        ..................f.....
                        ........................
                        ........................
        """))
    elif mySprite.ax < 0:
        mySprite.set_image(img("""
            ..............fff.......
                        .........fffff..........
                        ......fffff....fff......
                        ...fff....fffff.........
                        ......fffff.............
                        ...fff....f.............
                        ...........f............
                        ...........f..ffff......
                        ........ffffff111f......
                        .....fff1111f1111ff.....
                        .....f111111f1111f.f....
                        .....ff11111f11111ff....
                        .....ff11111f11111f.f...
                        .....ff11111111111f.f...
                        .....f.f11111111111f.f..
                        .....f.f111111111fff..f.
                        .....f.f111ffffff.....f.
                        .....f.ffff............f
                        .....f..................
                        .....f..................
                        .....f..................
                        .....f..................
                        ........................
                        ........................
        """))
    elif mySprite.vx > 0:
        mySprite.set_image(img("""
            ........................
                        ........................
                        .....fffffffffffffff....
                        ............f...........
                        .....fffffffffffffff....
                        ............f...........
                        ............f...........
                        ............f...........
                        ......fffffffffffff.....
                        ......f11111f11111f.....
                        ......f11111f11111f.....
                        .....ff11111f11111ff....
                        .....ff11111f11111ff....
                        .....ff11111111111ff....
                        ....f.f11111111111f.f...
                        ....f.f11111111111f.f...
                        ....f.fffffffffffff.f...
                        ...f.................f..
                        ...f.................f..
                        ...f.................f..
                        ..f...................f.
                        ........................
                        ........................
                        ........................
        """))
    elif mySprite.vx < 0:
        mySprite.set_image(img("""
            ........................
                        ........................
                        .....fffffffffffffff....
                        ............f...........
                        .....fffffffffffffff....
                        ............f...........
                        ............f...........
                        ............f...........
                        ......fffffffffffff.....
                        ......f11111f11111f.....
                        ......f11111f11111f.....
                        .....ff11111f11111ff....
                        .....ff11111f11111ff....
                        .....ff11111111111ff....
                        ....f.f11111111111f.f...
                        ....f.f11111111111f.f...
                        ....f.fffffffffffff.f...
                        ...f.................f..
                        ...f.................f..
                        ...f.................f..
                        ..f...................f.
                        ........................
                        ........................
                        ........................
        """))
    else:
        mySprite.set_image(img("""
            ........................
                        ........................
                        .....fffffffffffffff....
                        ............f...........
                        .....fffffffffffffff....
                        ............f...........
                        ............f...........
                        ............f...........
                        ......fffffffffffff.....
                        ......f11111f11111f.....
                        ......f11111f11111f.....
                        .....ff11111f11111ff....
                        .....ff11111f11111ff....
                        .....ff11111111111ff....
                        ....f.f11111111111f.f...
                        ....f.f11111111111f.f...
                        ....f.fffffffffffff.f...
                        ...f.................f..
                        ...f.................f..
                        ...f.................f..
                        ..f...................f.
                        ........................
                        ........................
                        ........................
        """))
game.on_update_interval(100, on_update_interval2)
