namespace SpriteKind {
    export const Switch = SpriteKind.create()
}
scene.onHitWall(SpriteKind.Player, function (sprite, location) {
    if (!(sprite.isHittingTile(CollisionDirection.Bottom))) {
        game.over(false)
    } else if (terminalVelocity()) {
        game.over(false)
    }
    if (flying) {
        if (tiles.tileAtLocationEquals(location, sprites.dungeon.purpleSwitchUp)) {
            tiles.setTileAt(location, sprites.dungeon.greenSwitchDown)
            flying = 0
        } else if (tiles.tileAtLocationEquals(location, sprites.dungeon.greenSwitchDown)) {
            tiles.setTileAt(location, sprites.dungeon.purpleSwitchUp)
            flying = 0
        }
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.ay += thrust
    flying = 1
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.ax += thrust
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.ax += thrust
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.ax += 0 - thrust
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.ax += 0 - thrust
})
controller.A.onEvent(ControllerButtonEvent.Released, function () {
    mySprite.ay += 0 - thrust
})
// def get_tile_type(x: number, y: number):
// global location
// location = tiles.get_tile_location(x, y)
// if tiles.tile_at_location_equals(location, sprites.dungeon.collectible_red_crystal):
// return -1
// elif tiles.tile_at_location_equals(location, sprites.dungeon.collectible_blue_crystal):
// return 1
// return 0
function terminalVelocity () {
    return mySprite.vy > 25
}
let flying = 0
let thrust = 0
let mySprite: Sprite = null
let success = 0
scene.setBackgroundColor(12)
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . b 5 5 b . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b d 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b d 5 5 b 1 f f 5 4 4 c . . 
    b b d b 5 5 5 d f b 4 4 4 4 b . 
    b d d c d 5 5 b 5 4 4 4 4 4 4 b 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Player)
mySprite.setPosition(1970, 1000)
mySprite.setPosition(16, 460)
mySprite.setPosition(16, 460)
scene.cameraFollowSprite(mySprite)
mySprite.ay = 20
mySprite.fx = 5
mySprite.fy = 5
thrust = -100
let terminal_velocity = 25
flying = 1
game.onUpdateInterval(100, function () {
    if (terminalVelocity()) {
        if (mySprite.ax > 0) {
            mySprite.setImage(img`
                .......fff..............
                ..........fffff.........
                ......fff....fffff......
                .........fffff....fff...
                .............fffff......
                .............f....fff...
                ............f...........
                ......ffff..f...........
                ......f111ffffff........
                ......f1111f1111fff.....
                ......f1111f111111f.....
                .....f11111f11111f......
                .....f11111f11111f......
                .....f11111111111f......
                ....f11111111111f.......
                ....fff111111111f.......
                .......ffffff111f.......
                .............ffff.......
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        } else if (mySprite.ax < 0) {
            mySprite.setImage(img`
                ..............fff.......
                .........fffff..........
                ......fffff....fff......
                ...fff....fffff.........
                ......fffff.............
                ...fff....f.............
                ...........f............
                ...........f..ffff......
                ........ffffff111f......
                .....fff1111f1111f......
                .....f111111f1111f......
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111111111f.....
                .......f11111111111f....
                .......f111111111fff....
                .......f111ffffff.......
                .......ffff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        } else if (mySprite.vx > 0) {
            mySprite.setImage(img`
                ........................
                ........................
                .....fffffffffffffff....
                ............f...........
                .....fffffffffffffff....
                ............f...........
                ............f...........
                ............f...........
                ......fffffffffffff.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111111111f.....
                ......f11111111111f.....
                ......f11111111111f.....
                ......fffffffffffff.....
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        } else if (mySprite.vy < 0) {
            mySprite.setImage(img`
                ........................
                ........................
                .....fffffffffffffff....
                ............f...........
                .....fffffffffffffff....
                ............f...........
                ............f...........
                ............f...........
                ......fffffffffffff.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111111111f.....
                ......f11111111111f.....
                ......f11111111111f.....
                ......fffffffffffff.....
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        } else {
            mySprite.setImage(img`
                ........................
                ........................
                .....fffffffffffffff....
                ............f...........
                .....fffffffffffffff....
                ............f...........
                ............f...........
                ............f...........
                ......fffffffffffff.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111f11111f.....
                ......f11111111111f.....
                ......f11111111111f.....
                ......f11111111111f.....
                ......fffffffffffff.....
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        }
    } else if (mySprite.ax > 0) {
        mySprite.setImage(img`
            .......fff..............
            ..........fffff.........
            ......fff....fffff......
            .........fffff....fff...
            .............fffff......
            .............f....fff...
            ............f...........
            ......ffff..f...........
            ......f111ffffff........
            .....ff1111f1111fff.....
            ....f.f1111f111111f.....
            ....ff11111f11111ff.....
            ...f.f11111f11111ff.....
            ...f.f11111111111ff.....
            ..f.f11111111111f.f.....
            .f..fff111111111f.f.....
            .f.....ffffff111f.f.....
            f............ffff.f.....
            ..................f.....
            ..................f.....
            ..................f.....
            ..................f.....
            ........................
            ........................
            `)
    } else if (mySprite.ax < 0) {
        mySprite.setImage(img`
            ..............fff.......
            .........fffff..........
            ......fffff....fff......
            ...fff....fffff.........
            ......fffff.............
            ...fff....f.............
            ...........f............
            ...........f..ffff......
            ........ffffff111f......
            .....fff1111f1111ff.....
            .....f111111f1111f.f....
            .....ff11111f11111ff....
            .....ff11111f11111f.f...
            .....ff11111111111f.f...
            .....f.f11111111111f.f..
            .....f.f111111111fff..f.
            .....f.f111ffffff.....f.
            .....f.ffff............f
            .....f..................
            .....f..................
            .....f..................
            .....f..................
            ........................
            ........................
            `)
    } else if (mySprite.vx > 0) {
        mySprite.setImage(img`
            ........................
            ........................
            .....fffffffffffffff....
            ............f...........
            .....fffffffffffffff....
            ............f...........
            ............f...........
            ............f...........
            ......fffffffffffff.....
            ......f11111f11111f.....
            ......f11111f11111f.....
            .....ff11111f11111ff....
            .....ff11111f11111ff....
            .....ff11111111111ff....
            ....f.f11111111111f.f...
            ....f.f11111111111f.f...
            ....f.fffffffffffff.f...
            ...f.................f..
            ...f.................f..
            ...f.................f..
            ..f...................f.
            ........................
            ........................
            ........................
            `)
    } else if (mySprite.vx < 0) {
        mySprite.setImage(img`
            ........................
            ........................
            .....fffffffffffffff....
            ............f...........
            .....fffffffffffffff....
            ............f...........
            ............f...........
            ............f...........
            ......fffffffffffff.....
            ......f11111f11111f.....
            ......f11111f11111f.....
            .....ff11111f11111ff....
            .....ff11111f11111ff....
            .....ff11111111111ff....
            ....f.f11111111111f.f...
            ....f.f11111111111f.f...
            ....f.fffffffffffff.f...
            ...f.................f..
            ...f.................f..
            ...f.................f..
            ..f...................f.
            ........................
            ........................
            ........................
            `)
    } else {
        mySprite.setImage(img`
            ........................
            ........................
            .....fffffffffffffff....
            ............f...........
            .....fffffffffffffff....
            ............f...........
            ............f...........
            ............f...........
            ......fffffffffffff.....
            ......f11111f11111f.....
            ......f11111f11111f.....
            .....ff11111f11111ff....
            .....ff11111f11111ff....
            .....ff11111111111ff....
            ....f.f11111111111f.f...
            ....f.f11111111111f.f...
            ....f.fffffffffffff.f...
            ...f.................f..
            ...f.................f..
            ...f.................f..
            ..f...................f.
            ........................
            ........................
            ........................
            `)
    }
})
